module "taskcluster" {
  source = "./taskcluster"

  deployment = "${var.deployment}"
  dpl        = "${var.dpl}"

  gcp_region  = "${var.gcp_region}"
  gcp_project = "${var.gcp_project}"
  aws_region  = "${var.aws_region}"
  aws_account = "${var.aws_account}"

  rabbitmq_vhost                         = "${var.rabbitmq_vhost}"
  cluster_name                           = "${var.cluster_name}"
  irc_name                               = "${var.irc_name}"
  irc_port                               = "${var.irc_port}"
  irc_real_name                          = "${var.irc_real_name}"
  azure_region                           = "${var.azure_region}"
  root_url                               = "${var.root_url}"
  rabbitmq_hostname                      = "${var.rabbitmq_hostname}"
  irc_nick                               = "${var.irc_nick}"
  irc_server                             = "${var.irc_server}"
  irc_password                           = "${var.irc_password}"
  github_private_pem                     = "${var.github_private_pem}"
  github_app_id                          = "${var.github_app_id}"
  notify_ses_arn                         = "${var.notify_ses_arn}"
  github_webhook_secret                  = "${var.github_webhook_secret}"
  gce_provider_gcp_project               = "${var.gcp_project}"
  gce_provider_image_name                = "${var.gce_provider_image_name}"
  web_server_mozilla_auth0_domain        = "${var.web_server_mozilla_auth0_domain}"
  web_server_mozilla_auth0_client_id     = "${var.web_server_mozilla_auth0_client_id}"
  web_server_mozilla_auth0_client_secret = "${var.web_server_mozilla_auth0_client_secret}"
  web_server_mozilla_auth0_audience      = "${var.web_server_mozilla_auth0_audience}"
  web_server_mozilla_auth0_scope         = "${var.web_server_mozilla_auth0_scope}"
  web_server_github_client_id            = "${var.web_server_github_client_id}"
  web_server_github_client_secret        = "${var.web_server_github_client_secret}"
}
